name: RSI Alert Bot

on:
  schedule:
    - cron: "0 * * * *"   # Ejecuta cada hora (en horario UTC)
  workflow_dispatch:       # Permite ejecución manual desde GitHub Actions

jobs:
  run-flow:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ⚙️ Configurar variables secretas
        run: |
          echo "Creando archivo de configuración..."
          echo "TELEGRAM_TOKEN = '${{ secrets.TELEGRAM_TOKEN }}'" > config.py
          echo "TELEGRAM_CHAT_ID = '${{ secrets.TELEGRAM_CHAT_ID }}'" >> config.py
          echo "TICKER = '${{ secrets.TICKER }}'" >> config.py

      - name: 🚀 Ejecutar flujo Prefect
        run: python flow.py
